server.port=8080
#server.address=0.0.0.0


spring.application.name=smartPos
spring.datasource.url=jdbc:postgresql://ep-soft-fog-a1dj8vuk-pooler.ap-southeast-1.aws.neon.tech/J2LAuto?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Idzx1YDF4kpR
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000

# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Timezone settings
spring.jackson.time-zone=Asia/Colombo
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Colombo

# CORS allowed origin
#app.cors.allowed-origin=https://truefrontend-ffazc0h9ejgwdrhf.canadacentral-01.azurewebsites.net
app.cors.allowed-origin=https://zealous-desert-0b4c91600.7.azurestaticapps.net
#app.cors.allowed-origin=https://www.trueenterprises.online
#app.cors.allowed-origin=http://localhost:4200
